zuul:
  routes:
    products:
      path: /api/v1/**
      url: https://course-web-app-java.herokuapp.com/
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image

zuul:
  routes:
    my-service:
      path: /my-service/**
      serviceId: my-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:Dev@2021@localhost:5000}/eureka/
