zuul:
  routes:
    heroku:
      path: /heroku/**
      url: https://course-web-app-java.herokuapp.com/api/v1/instructors/rakesh/courses
    links:
      path: /links/**
      url: https://mysterious-plains-07158.herokuapp.com
    images:
      path: /image/**
      url: https://course-web-app-java.herokuapp.com/api/v1/instructors/rakesh/courses

eureka:
  client:
    enabled: false
