zuul:
  routes:
    products:
      path: /api/v1/instructors/**
      url: https://course-web-app-java.herokuapp.com/
    my-service:
      path: /my-service/**
      serviceId: my-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:Dev@2021@localhost:5000}/eureka/
