zuul:
  routes:
    products:
      path: /api/v1/**
      url: https://course-web-app-java.herokuapp.com/
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image

eureka:
  client:
    enabled: false
